// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltamqzgtaklzqmmmxkan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0YW1xemd0YWtsenFtbW14a2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODI0ODcsImV4cCI6MjA1OTc1ODQ4N30.703-LnMyewj3exHZWzDAew3RZNsdJYQo2GyshF6Xxr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);